# Generated by Django 4.2.2 on 2024-03-14 18:28

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_vendor_date_alter_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                default="vendor.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
