# Generated by Django 4.2.2 on 2024-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_life_product_mdf_product_stock_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='10 days', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_account',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
    ]
