# Generated by Django 4.2.2 on 2024-03-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_mdf_product_mdg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mdg',
            new_name='mfg',
        ),
    ]
