# Generated by Django 4.2.2 on 2024-03-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_mdg_product_mfg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock_account",
            new_name="stock_count",
        ),
    ]
