# Generated by Django 4.2.2 on 2024-04-08 12:31

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="saved",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=12),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="shipping_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="zaqwsxcderfvbgtyhnmjuiklop12345678090",
                blank=True,
                length=5,
                max_length=8,
                null=True,
                prefix="sku",
            ),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="tracking_website_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=12),
        ),
    ]
