# Generated by Django 4.2.2 on 2024-04-08 14:49

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_cartorder_address_cartorder_city_cartorder_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="oid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345678090",
                blank=True,
                length=5,
                max_length=8,
                null=True,
                prefix="sku",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345678090",
                blank=True,
                length=5,
                max_length=8,
                null=True,
                prefix="sku",
            ),
        ),
    ]
