# Generated by Django 4.2.2 on 2024-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_cartorder_oid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("discount", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Coupon",
            },
        ),
    ]
