# Generated by Django 4.2.2 on 2024-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="coupons",
            field=models.ManyToManyField(blank=True, to="core.coupon"),
        ),
    ]
