# Generated by Django 4.2.2 on 2024-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="exit", max_length=255),
            preserve_default=False,
        ),
    ]
