# Generated by Django 4.2.2 on 2024-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_profile_address_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
