# Generated by Django 4.2.2 on 2024-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0006_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
